"""

Django settings for learnalytics project.


Generated by 'django-admin startproject' using Django 6.0.


For more information on this file, see

https://docs.djangoproject.com/en/6.0/topics/settings/


For the full list of settings and their values, see

https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os

from dotenv import load_dotenv

from pathlib import Path

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production

# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!



# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = False


ALLOWED_HOSTS = [

    "127.0.0.1",

    "localhost",

    "learnalytics.onrender.com",

] 


print("FINAL ALLOWED_HOSTS =", ALLOWED_HOSTS)



# Application definition


INSTALLED_APPS = [

    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',

    'django_extensions',

    #my apps

    'rest_framework',

    'authentication',
    'students',

    'feedback',

    'performance',

    'visualization',

    'security',

    'teacher',

]


MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'learnalytics.middleware.AdminRateLimitMiddleware', #api rate limit for admin login

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',  # for serving static files in production

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]


ROOT_URLCONF = 'learnalytics.urls'


TEMPLATES = [

    {

        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [BASE_DIR / "templates"],  #  important for template overrides

        "APP_DIRS": True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.request",  # required for admin & jazzmin

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",

            ],

        }

    },

]



WSGI_APPLICATION = 'learnalytics.wsgi.application'



# Database

# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {

    "default": {

        "ENGINE": "django.db.backends.sqlite3",

        "NAME": BASE_DIR / "db.sqlite3",

    }

}



# Password validation

# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]


# Static files (CSS, JavaScript, Images)

# https://docs.djangoproject.com/en/6.0/howto/static-files/


STATIC_URL = '/static/'

STATICFILES_DIRS = [BASE_DIR / "static"]  # for development; collectstatic will gather from here

STATIC_ROOT =  os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


MEDIA_ROOT = BASE_DIR / "media"

MEDIA_URL = '/media/'


# Admin/Teacher must login again after closing browser

SESSION_EXPIRE_AT_BROWSER_CLOSE = True


LOGIN_URL = "/admin/login/"

LOGIN_REDIRECT_URL = "/teacher/dashboard/"


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"   # Local Time-Zone for your project

USE_I18N = True

USE_TZ = True



EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = 'admin@learnalytics.com'


SECRET_KEY = os.getenv("SECRET_KEY")


#SECURITY

# HTTPS (Render uses proxy)

#SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

#SECURE_SSL_REDIRECT = True


# Cookies

#SESSION_COOKIE_SECURE = True

#CSRF_COOKIE_SECURE = True


# Headers

#SECURE_BROWSER_XSS_FILTER = True

#SECURE_CONTENT_TYPE_NOSNIFF = True

#X_FRAME_OPTIONS = 'DENY'


# HSTS (force HTTPS long-term)

#SECURE_HSTS_SECONDS = 31536000

#SECURE_HSTS_INCLUDE_SUBDOMAINS = True

#SECURE_HSTS_PRELOAD = True


# CSRF

CSRF_TRUSTED_ORIGINS = [

    "https://learnalytics.onrender.com"

]


LOGGING = {

    'version': 1,

    'disable_existing_loggers': False,

    'handlers': {

        'file': {

            'level': 'WARNING',

            'class': 'logging.FileHandler',

            'filename': 'security.log',

        },

    },

    'loggers': {

        'django.security': {

            'handlers': ['file'],

            'level': 'WARNING',

            'propagate': True,

        },

    },

}

#blocking creation of superusers via createsuperuser command in production  
